---
- name: Create vnet
  azure_rm_virtualnetwork:
    name: vnet-hedvig
    location: '{{ region }}'
    resource_group: rg-hedvig
    address_prefixes_cidr:
      - '{{ cidr.base }}'
    state: present