- name: Copy software
  hosts: deployment
  vars_files:
    - ./vars.yaml
  tasks:
    - name: Copy the software from the bucket
      command: "az storage blob download --account-name sahvsoftware --container schvsoftware --name hedvig_41.zip --file /tmp/hedvig.zip"
      register: out
    - debug: var=out.stdout_lines
    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /tmp/hedvig.zip
        dest: /tmp/.
        remote_src: yes
    - name: Change file ownership, group and permissions
      file:
        path: /tmp/*.bin
        owner: admin
        group: admin
        mode: '0755'
      become: yes