- name: Local ssh maintenance
  hosts: localhost
  connection: local
  vars_files:
    - "{{ lookup('env', 'PWD') }}/vars.yaml"  
  tasks:
    - name: Local ssh maintenance
      include_role:
        name: known_hosts