# - name: add host
#   hosts:
#     localhost
#   connection: local
#   vars_files:
#     - "{{ lookup('env', 'PWD') }}/vars.yaml"  
#   tasks:
#     - name: Add the jump server IP to the host list
#       add_host:
#         hostname: '{{ jump_server }}'
#         groups: jump
- name: Prepare the jump server to allow remote login and use of hedvig console
  hosts:
    - jump
  vars_files:
    - "{{ lookup('env', 'PWD') }}/vars.yaml"  
  tasks:
    - name: Prepare the jump server
      include_role:
        name: jump
- name: Prepare the other servers
  hosts: 
    - proxy
    - deployment
    - storagenodes
  vars_files:
    - "{{ lookup('env', 'PWD') }}/vars.yaml"
  tasks:
    - name: Prepare proxy, deployment, and storage nodes
      include_role:
        name: common
- name: Prepare the other servers
  hosts: 
    - deployment
  vars_files:
    - "{{ lookup('env', 'PWD') }}/vars.yaml"
  tasks:
    - name: Further deployment server prep
      include_role:
        name: deployment