- name: Create Azure resources
  hosts: localhost
  connection: local
  tasks:
    - name: Remove resource group
      azure_rm_resourcegroup:
        name: rghedvigsw
        location: eastus
        force_delete_nonempty: yes
        state: absent