- name: Prepare VMs for hedvig installation
  hosts:
    - proxy
    - deployment
    - storagenodes
  vars_files:
    - "{{ lookup('env', 'PWD') }}/vars.yaml"
    - ./packages.yaml
  tasks:
    - name: Set root password
      become: true
      user:
        name: root
        password: "{{ pwd | password_hash('sha512') }}"
    - name: Create admin group
      become: true
      group:
        name: admin
        state: present
    - name: Create admin user password and append groups
      become: true
      user:
        name: admin
        password: "{{ pwd | password_hash('sha512') }}"
        groups: admin, wheel
        append: yes
        state: present
        generate_ssh_key: yes
    - name: Modify wheel group to allow password-less sudo operations (for admin user)
      become: true
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^# %wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
        backup: yes
    - name: Install additional packages
      yum:
        name: "{{ packages }}"
        state: latest
      become: yes
    - name: Install pip
      easy_install:
        name: pip
        state: latest
      become: yes
    - name: Install fabric
      pip:
        name: fabric
      become: yes
- name: Install ansible
  hosts: deployment
  vars_files:
    - "{{ lookup('env', 'PWD') }}/vars.yaml"
  tasks:
    - name: install ansible (deployment server only)
      yum:
        name: ansible
        state: latest
      become: true
- name: Setup
  hosts:
    - proxy
    - deployment
    - storagenodes
  vars_files:
    - "{{ lookup('env', 'PWD') }}/vars.yaml"
  tasks:
    - name: Disable password auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "#PasswordAuthentication"
      become: yes
    - name: Disable resource disk
      lineinfile:
        path: /etc/waagent.conf
        regexp: "^ResourceDisk.Format=y"
        line: "ResourceDisk.Format=n"
      become: yes
    - name: Disable selinux 0
      lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX=enforcing"
        line: "SELINUX=disabled"
      become: yes
    - name: Disable selinux 1
      lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX=permissive"
        line: "SELINUX=disabled"
      become: yes
    - name: Stop and disable firewalld to enable graphical installer
      service:
        name: firewalld
        state: stopped
        enabled: False  
      become: yes
    - name: Restart server
      reboot:
      become: yes