- name: Add new ip / key combination to known_hosts to prevent annoying prompts
  local_action: shell ssh-keyscan {{ jump_server }} >> ~/.ssh/known_hosts
- name: Create the inventory file with the resolved jump server ip
  template:
    src: hosts.yaml.j2
    dest: "{{ lookup('env', 'PWD') }}/hosts.yaml"