- name: Create resource group
  azure_rm_resourcegroup:
    name: rghedvigsw
    location: eastus
    state: present
- name: Create storage account
  azure_rm_storageaccount:
    name: sahedvigsw
    resource_group: rghedvigsw
    account_type: Standard_LRS
    allow_blob_public_access: False
    state: present
- name: Create storage container and upload software
  azure_rm_storageblob:
    resource_group: rghedvigsw
    storage_account_name: sahedvigsw        
    container: schedvigsw
    blob: "{{ software_filename }}"
    src: "/tmp/{{ software_filename }}"
    state: present