- name: Create Azure compute resources
  hosts: localhost
  connection: local
  vars_files:
    - ./azure-vars.yaml
  tasks:
    - name: Create vm-jump
      azure_rm_virtualmachine:
        name: vm-jump
        resource_group: rg-hedvig
        subnet_name: sn-public
        network_interface_names: ["ni-jump"]
        vm_size: "{{ vm_size.proxy }}"
        os_type: Linux
        os_disk_name: vm-jump-disk-os
        os_disk_caching: ReadWrite
        storage_account_name: sahedvig
        admin_username: azureuser
        short_hostname: vm-jump
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: "/home/azureuser/.ssh/authorized_keys"
            key_data: "{{ lookup('file', '{{ key_path_public }}') }}"
        image:
          publisher: OpenLogic
          offer: CentOS
          sku: '{{ os_version }}'
          version: latest
        state: present
    - name: Create vm-proxy
      azure_rm_virtualmachine:
        name: vm-proxy
        resource_group: rg-hedvig
        subnet_name: sn-private
        network_interface_names: ["ni-proxy"]
        vm_size: "{{ vm_size.proxy }}"
        managed_disk_type: '{{ storage_account_type }}'
        os_type: Linux
        os_disk_name: vm-proxy-disk-os
        os_disk_caching: ReadWrite
        storage_account_name: sahedvig
        admin_username: azureuser
        short_hostname: vm-proxy
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: "/home/azureuser/.ssh/authorized_keys"
            key_data: "{{ lookup('file', '{{ key_path_public }}') }}"
        image:
          publisher: OpenLogic
          offer: CentOS
          sku: '{{ os_version }}'
          version: latest
        data_disks:
          - lun: 0
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 64
        state: present
    - name: Create vm-deployment
      azure_rm_virtualmachine:
        name: vm-deployment
        resource_group: rg-hedvig
        subnet_name: sn-private
        network_interface_names: ["ni-deployment"]
        vm_size: "{{ vm_size.deployment }}"
        managed_disk_type: '{{ storage_account_type }}'
        os_type: Linux
        os_disk_name: vm-deployment-disk-os
        os_disk_caching: ReadWrite
        os_disk_size_gb: 128
        storage_account_name: sahedvig
        admin_username: azureuser
        short_hostname: vm-deployment
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: "/home/azureuser/.ssh/authorized_keys"
            key_data: "{{ lookup('file', '{{ key_path_public }}') }}"
        image:
          publisher: OpenLogic
          offer: CentOS
          sku: '{{ os_version }}'
          version: latest
        data_disks:
          - lun: 0
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 64
        state: present

# vm-storagenode[0-2]
    - name: Create storage node instances
      azure_rm_virtualmachine:
        name: "vm-{{ item }}"
        resource_group: rg-hedvig
        subnet_name: sn-private
        network_interface_names: ["ni-{{ item }}"]
        vm_size: "{{ vm_size.storagenode }}"
        managed_disk_type: '{{ storage_account_type }}'
        os_type: Linux
        os_disk_name: "vm-{{ item }}-disk-os"
        os_disk_caching: ReadWrite
        os_disk_size_gb: 128
        storage_account_name: sahedvig
        admin_username: azureuser
        short_hostname: "vm-{{ item }}"
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: "/home/azureuser/.ssh/authorized_keys"
            key_data: "{{ lookup('file', '{{ key_path_public }}') }}"
        image:
          publisher: OpenLogic
          offer: CentOS
          sku: '{{ os_version }}'
          version: latest
        data_disks:
          # cache
          - lun: 0
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 40
          # metadata
          - lun: 1
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
          # data
          - lun: 2
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
          - lun: 3
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
          - lun: 4
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
          - lun: 5
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
          - lun: 6
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
          - lun: 7
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
          - lun: 8
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
          - lun: 9
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
          - lun: 10
            managed_disk_type: '{{ storage_account_type }}'
            disk_size_gb: 24
        state: present
      loop:
        - storagenode0
        - storagenode1
        - storagenode2