- name: Destroy Azure resources
  hosts: localhost
  connection: local
  tasks:
    - name: Remove resource group
      azure_rm_resourcegroup:
        name: rg-hedvig
        location: eastus
        force_delete_nonempty: yes
        state: absent