- name: Create Azure resources
  hosts: localhost
  connection: local
  tasks:
    - name: Destroy Azure resources
      terraform:
        project_path: "{{ lookup('env', 'PWD') }}/tasks/cloud/terraform/azure/resources/"
        state: absent