- name: Install Azure CLI
  hosts:
    - deployment
  vars_files:
    - "{{ lookup('env', 'PWD') }}/vars.yaml"
  tasks:
    - name: Add key
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
      become: true
    - name: Add repository from MSFT
      yum_repository:
        description: MSFT repo
        name: azure-cli.repo
        baseurl: https://packages.microsoft.com/yumrepos/azure-cli
        state: present
      become: true
    - name: install the latest version of Azure CLI
      yum:
        name: azure-cli
        state: latest
      become: true
    - name: create directory
      file:
        path: /tmp/hedvig
        state: directory
        mode: "0777"
      become: yes