- name: Add key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: true
- name: Add repository from MSFT
  yum_repository:
    description: MSFT repo
    name: azure-cli.repo
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    state: present
  become: true
- name: Install ansible and azure-cli
  yum:
    name: 
      - azure-cli
      - ansible
    state: latest
  become: true
- name: Load Ansible azure collection
  command: ansible-galaxy collection install -c azure.azcollection
- name: Load Python modules to support azure
  pip:
    requirements: ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
    state: present
- name: create directory
  file:
    path: /tmp/hedvig
    state: directory
    mode: "0777"
  become: yes
- name: Push hv_deploy.cfg
  copy:    
    src: hv_deploy.cfg
    dest: /tmp/hedvig/hv_deploy.cfg
- name: push vars
  copy:
    src: "{{ lookup('env', 'PWD') }}/vars.yaml"
    dest: /tmp/hedvig/vars.yaml
    backup: yes
- name: push ansible file
  copy:
    src: main2.yaml
    dest: /tmp/hedvig/main2.yaml
    backup: yes
- name: Download software from bucket to local dir
  azure_rm_storageblob:
    resource_group: rghedvigsw
    storage_account_name: sahedvigsw        
    container: schedvigsw
    blob: "{{ software_filename }}"
    dest: /tmp/hedvig.zip
    state: present