- name: Create Azure resources
  hosts: localhost
  vars_files:
    - ./vars.yaml
  connection: local
  tasks:
    - name: Create Azure resources
      terraform:
        project_path: "{{ lookup('env', 'PWD') }}/../terraform/azure/"
        force_init: yes
        state: present
      register: tfoutput
    - name: Capture output of terraform step to text file for the jump server IP
      copy:
        content: "{{ tfoutput.stdout }}"
        dest: "/tmp/tf.output"