- name: Create Azure bucket for software and upload the software
  hosts: localhost
  vars_files:
    - ./vars.yaml
  connection: local
  tasks:
    - name: Create Azure resource group, bucket to store software
      terraform:
        project_path: "{{ lookup('env', 'PWD') }}/../terraform/azure/swbucket/"
        force_init: yes
        state: present
    - name: Upload the software to the bucket
      command: "az storage blob upload --account-name sahedvigsw --container schedvigsw --name {{ software_filename }} --file /tmp/{{ software_filename }}"