all:
  vars:
    ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -J azureuser@{{ jump_server }}"
    ansible_user: azureuser
  children:
    jump:
      hosts:
        "{{ jump_server }}"
    proxy:
      hosts:
        vm-proxy:
    deployment:
      hosts:
        vm-deployment:
    storagenodes:
      hosts:
        vm-storagenode[0:2]: