- import_playbook: ./resources_create.yaml
# get the public IP of the jump / jump_server server and append to vars.yaml (automation opportunity)
- import_playbook: ./known_hosts.yaml
# optional: make sure connectivity to all servers is in place
- import_playbook: ./validate.yaml
- import_playbook: ./setup.yaml
# manually login to vm-deployment server and run az login
# ssh -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -J azureuser@<<jump server ip>> azureuser@vm-deployment
# az login
- import_playbook: ./copy_software.yaml
- import_playbook: ./install_hedvig.yaml