packages:
  - "@Base"
  - abrt
  - abrt-addon-ccpp
  - abrt-addon-kerneloops
  - abrt-addon-pstoreoops
  - abrt-addon-python
  - abrt-addon-vmcore
  - abrt-addon-xorg
  - abrt-cli
  - abrt-console-notification
  - abrt-dbus
  - abrt-libs
  - abrt-python
  - abrt-retrace-client
  - abrt-tui
  - acl
  - adwaita-cursor-theme
  - adwaita-icon-theme
  - aic94xx-firmware
  - alsa-firmware
  - alsa-lib
  - alsa-tools-firmware
  - apr
  - apr-util
  - at
  - at-spi2-atk
  - at-spi2-core
  - atk
  - attr
  - audit
  - audit-libs
  - augeas-libs
  - authconfig
  - avahi-libs
  - awscli
  - basesystem
  - bash
  - bash-completion
  - bc
  - bind-libs
  - bind-libs-lite
  - bind-license
  - bind-utils
  - binutils
  - biosdevname
  - blktrace
  - boost-date-time
  - boost-system
  - boost-thread
  - bridge-utils
  - btrfs-progs
  - bzip2
  - bzip2-libs
  - ca-certificates
  - cairo
  - cairo-gobject
  - centos-indexhtml
  - centos-logos
  - centos-release
  - chkconfig
  - chrony
  - colord-libs
  - coreutils
  - cpan
  - cpio
  - cracklib
  - cracklib-dicts
  - crda
  - createrepo
  - cronie
  - cronie-anacron
  - crontabs
  - cryptsetup
  - cryptsetup-libs
  - cups-libs
  - curl
  - cyrus-sasl-lib
  - cyrus-sasl-plain
  - dbus
  - dbus-glib
  - dbus-libs
  - dbus-python
  - dconf
  - dejavu-fonts-common
  - dejavu-sans-mono-fonts
  - deltarpm
  - desktop-file-utils
  - device-mapper
  - device-mapper-event
  - device-mapper-event-libs
  - device-mapper-libs
  - device-mapper-persistent-data
  - dhclient
  - dhcp
  - dhcp-common
  - dhcp-libs
  - diffutils
  - dmidecode
  - dmraid
  - dmraid-events
  - dnsmasq
  - dosfstools
  - dracut
  - dracut-config-rescue
  - dracut-network
  - dyninst
  - e2fsprogs
  - e2fsprogs-libs
  - ebtables
  - ed
  - elfutils
  - elfutils-default-yama-scope
  - elfutils-libelf
  - elfutils-libs
  - emacs
  - emacs-common
  - emacs-filesystem
  - epel-release
  - ethtool
  - expat
  - expect
  - file
  - file-libs
  - filesystem
  - findutils
  - fipscheck
  - fipscheck-lib
  - firewalld
  - firewalld-filesystem
  - fontconfig
  - fontpackages-filesystem
  - fprintd
  - fprintd-pam
  - freetype
  - ftp
  - fuse
  - fuse-libs
  - fxload
  - gawk
  - GConf2
  - gdb
  - gdbm
  - gdk-pixbuf2
  - GeoIP
  - gettext
  - gettext-libs
  - ghostscript
  - ghostscript-fonts
  - giflib
  - glib-networking
  - glib2
  - glibc
  - glibc-common
  - gmp
  - gnupg2
  - gnutls
  - gobject-introspection
  - gpgme
  - gpm-libs
  - graphite2
  - grep
  - groff-base
  - grub2
  - grub2-common
  - grub2-pc
  - grub2-pc-modules
  - grub2-tools
  - grub2-tools-extra
  - grub2-tools-minimal
  - grubby
  - gsettings-desktop-schemas
  - gtk-update-icon-cache
  - gtk3
  - gzip
  - hardlink
  - harfbuzz
  - hicolor-icon-theme
  - hostname
  - httpd
  - httpd-tools
  - hunspell
  - hunspell-en
  - hunspell-en-GB
  - hunspell-en-US
  - hwdata
  - ilmbase
  - ImageMagick
  - info
  - initscripts
  - iproute
  - iprutils
  - ipset
  - ipset-libs
  - iptables
  - iputils
  - irqbalance
  - ivtv-firmware
  - iw
  - iwl100-firmware
  - iwl1000-firmware
  - iwl105-firmware
  - iwl135-firmware
  - iwl2000-firmware
  - iwl2030-firmware
  - iwl3160-firmware
  - iwl3945-firmware
  - iwl4965-firmware
  - iwl5000-firmware
  - iwl5150-firmware
  - iwl6000-firmware
  - iwl6000g2a-firmware
  - iwl6000g2b-firmware
  - iwl6050-firmware
  - iwl7260-firmware
  # - iwl7265-firmware
  - jansson
  - jasper-libs
  - jbigkit-libs
  - json-c
  - json-glib
  - kbd
  - kbd-legacy
  - kbd-misc
  - kernel
  - kernel-tools
  - kernel-tools-libs
  - kexec-tools
  - keyutils-libs
  - kmod
  - kmod-libs
  - kpartx
  - kpatch
  - krb5-libs
  - langtable
  - langtable-data
  - langtable-python
  - lcms2
  - ledmon
  - less
  - libacl
  - libaio
  - libassuan
  - libattr
  - libblkid
  - libcap
  - libcap-ng
  - libcom_err
  - libconfig
  - libcroco
  - libcurl
  - libdaemon
  - libdb
  - libdb-utils
  - libdnet
  - libdrm
  - libdwarf
  - libedit
  - libepoxy
  - libestr
  - libevent
  - libfastjson
  - libffi
  - libfontenc
  - libfprint
  - libgcc
  - libgcrypt
  - libgomp
  - libgpg-error
  - libgudev1
  - libgusb
  - libICE
  - libicu
  - libidn
  - libjpeg-turbo
  - liblockfile
  - libmnl
  - libmodman
  - libmount
  - libmspack
  - libndp
  - libnetfilter_conntrack
  - libnfnetlink
  - libnl
  - libnl3
  - libnl3-cli
  - libotf
  - libpcap
  - libpciaccess
  - libpipeline
  - libpng
  - libproxy
  - libpwquality
  - libreport
  - libreport-centos
  - libreport-cli
  - libreport-filesystem
  - libreport-plugin-mailx
  - libreport-plugin-mantisbt
  - libreport-plugin-rhtsupport
  - libreport-plugin-ureport
  - libreport-python
  - libreport-web
  - librsvg2
  - libseccomp
  - libselinux
  - libselinux-python
  - libselinux-utils
  - libsemanage
  - libsepol
  - libSM
  - libsoup
  - libss
  - libssh2
  - libsss_idmap
  - libsss_nss_idmap
  - libstdc++
  - libstoragemgmt
  - libstoragemgmt-python
  - libstoragemgmt-python-clibs
  - libsysfs
  - libtar
  - libtasn1
  - libteam
  - libthai
  - libtiff
  - libtirpc
  - libtool-ltdl
  - libunistring
  - libusbx
  - libuser
  - libutempter
  - libuuid
  - libverto
  - libwebp
  - libwmf-lite
  - libX11
  - libX11-common
  - libXau
  - libXaw
  - libxcb
  - libXcomposite
  - libXcursor
  - libXdamage
  - libXext
  - libXfixes
  - libXfont
  - libXft
  - libXi
  - libXinerama
  - libxml2
  - libxml2-python
  - libXmu
  - libXpm
  - libXrandr
  - libXrender
  - libxshmfence
  - libxslt
  - libXt
  - libXtst
  - libXxf86vm
  - libyaml
  - linux-firmware
  - lm_sensors-libs
  - logrotate
  - lsof
  - lsscsi
  - lua
  - lvm2
  - lvm2-libs
  - lzo
  - m17n-db
  - m17n-lib
  - mailcap
  - mailx
  - make
  - man-db
  - man-pages
  - man-pages-overrides
  - mariadb-libs
  - mdadm
  - mesa-libEGL
  - mesa-libgbm
  - mesa-libGL
  - mesa-libglapi
  - microcode_ctl
  - mlocate
  - mozjs17
  - mtr
  - nano
  - ncurses
  - ncurses-base
  - ncurses-libs
  - net-tools
  - nettle
  - NetworkManager
  - NetworkManager-libnm
  - NetworkManager-ppp
  - NetworkManager-team
  - NetworkManager-tui
  - NetworkManager-wifi
  - newt
  - newt-python
  - nmap-ncat
  - nspr
  - nss
  - nss-pem
  - nss-softokn
  - nss-softokn-freebl
  - nss-sysinit
  - nss-tools
  - nss-util
  - ntpdate
  - ntsysv
  - numactl-libs
  - open-vm-tools
  - OpenEXR-libs
  - openldap
  - openssh
  - openssh-clients
  - openssh-server
  - openssl
  - openssl-libs
  - os-prober
  - p11-kit
  - p11-kit-trust
  - pam
  - pango
  - parted
  - passwd
  - pciutils
  - pciutils-libs
  - pcre
  - perl
  - perl-Carp
  - perl-constant
  - perl-Data-Dumper
  - perl-Digest
  - perl-Digest-MD5
  - perl-Encode
  - perl-Exporter
  - perl-File-Path
  - perl-File-Temp
  - perl-Filter
  - perl-Getopt-Long
  - perl-HTTP-Tiny
  - perl-libs
  - perl-macros
  - perl-parent
  - perl-PathTools
  - perl-Pod-Escapes
  - perl-Pod-Perldoc
  - perl-Pod-Simple
  - perl-Pod-Usage
  - perl-podlators
  - perl-Scalar-List-Utils
  - perl-Socket
  - perl-Storable
  - perl-Text-ParseWords
  - perl-threads
  - perl-threads-shared
  - perl-Time-HiRes
  - perl-Time-Local
  - pinentry
  - pinfo
  - pixman
  - pkgconfig
  - plymouth
  - plymouth-core-libs
  - plymouth-scripts
  - pm-utils
  - policycoreutils
  - polkit
  - polkit-pkla-compat
  - poppler-data
  - popt
  - postfix
  - ppp
  - procps-ng
  - psacct
  - psmisc
  - pth
  - pygobject2
  - pygpgme
  - pyliblzma
  - python
  - python-augeas
  - python-backports
  - python-backports-ssl_match_hostname
  - python-chardet
  - python-configobj
  - python-dateutil
  - python-decorator
  - python-deltarpm
  - python-devel
  - python-dmidecode
  - python-docutils
  - python-firewall
  - python-gobject-base
  - python-iniparse
  - python-kitchen
  - python-libs
  - python-linux-procfs
  - python-perf
  - python-pillow
  - python-pycurl
  - python-pyudev
  - python-schedutils
  - python-setuptools
  - python-six
  - python-slip
  - python-slip-dbus
  - python-urlgrabber
  - python2-futures
  - python2-jmespath
  - python2-pyasn1
  - pyxattr
  - PyYAML
  - qrencode-libs
  - quota
  - quota-nls
  - rdate
  - rdma-core
  - readline
  - rest
  - rfkill
  - rng-tools
  - rootfiles
  - rpcbind
  - rpm
  - rpm-build-libs
  - rpm-libs
  - rpm-python
  - rsync
  - rsyslog
  - satyr
  - scl-utils
  - sed
  - selinux-policy
  - selinux-policy-targeted
  - setserial
  - setup
  - setuptool
  - sg3_utils-libs
  - sgpio
  - shadow-utils
  - shared-mime-info
  - slang
  - smartmontools
  - snappy
  - sos
  - sqlite
  - sshpass
  - sssd-client
  - strace
  - sudo
  - sysstat
  - systemd
  - systemd-libs
  - systemd-python
  - systemd-sysv
  - systemtap-runtime
  - sysvinit-tools
  - tar
  - tcl
  - tcp_wrappers
  - tcp_wrappers-libs
  - tcpdump
  - tcsh
  - teamd
  - telnet
  - tftp
  - tftp-server
  - time
  - tmux
  - traceroute
  - trousers
  - tuned
  - tzdata
  - unzip
  - urw-fonts
  - usb_modeswitch
  - usb_modeswitch-data
  - usbutils
  - usermode
  - ustr
  - util-linux
  - vim-common
  - vim-enhanced
  - vim-filesystem
  - vim-minimal
  - virt-what
  - wget
  - which
  - words
  - wpa_supplicant
  - xdg-utils
  - xfsdump
  - xfsprogs
  - xinetd
  - xmlrpc-c
  - xmlrpc-c-client
  - xmlsec1
  - xmlsec1-openssl
  - xorg-x11-font-utils
  - xz
  - xz-libs
  - yajl
  - yum
  - yum-langpacks
  - yum-metadata-parser
  - yum-plugin-fastestmirror
  - yum-utils
  - zip
  - zlib
#  - gpg-pubkey
#  - htop
#  - ncftp
#  - python-colorama
#  - python-pip
#  - python2-botocore # need to install with pip?
#  - python2-rsa
#  - python2-s3transfer
# - iperf