- name: Generate keys and create Azure resources
  hosts: localhost
  vars_files: 
    - ./vars.yaml
  connection: local
  tasks:
    - name: Generate keys
      openssh_keypair:
        force: yes
        mode: '0400'
        size: 2048
        path: ~/.ssh/hedvig
    - name: Add keys
      shell: ssh-add ~/.ssh/hedvig
    - name: Create Azure resources
      terraform:
        project_path: "{{ lookup('env', 'PWD') }}/../terraform/azure/"
        state: present